import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/ThemeProvider';
import config from '@/config/env';
import { TableDevLinks } from '@/components/TableDevLinks';
import { Toaster } from '@/components/ui/sonner';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <html lang="en" suppressHydrationWarning>
                <head />
                <body>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        {children}
                        {config.PUBLIC_NODE_ENV === 'development' && <TableDevLinks />}
                        <Toaster />
                    </ThemeProvider>
                </body>
            </html>
        </>
    );
}
